name: Publish Docker image
run-name: some testing build
on:
  [push]
##  push:
##    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: GitHub Tag Name
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Checkout blax-b repo
        uses: actions/checkout@v3
        with:
          path: 'blax-b/'
          ref: "${{  github.ref_name }}"
          repository: 'tskuit/blax-b'

##      - name: Checkout blax-b repo
##        uses: actions/checkout@v3
##        with:
##          path: 'blax-b/'
##          ref: "${{  github.ref_name }}"
##          repository: 'tskuit/blax-b'


##      -
##        name: Build and push
##        uses: docker/build-push-action@v4
##        with:
##          tags: blax/app:latest
##
