name: remote call
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: main
#      workflow2_github_account:
#        description: 'GitHub Account Owner'
#        required: true
#        default: ':userName'
#
#      workflow2_repo_github:
#        description: 'repo-name'
#        required: true
#        default: ':repoName' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Remote build
        uses: docker/setup-buildx-action@v2

      - name: Remote tags
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"

      - name: Remote checkout blax-b repo
        uses: actions/checkout@v3
        with:
          path: 'blax-b/'
          ref: "${{ github.ref_name }}"
          repository: 'tskuit/blax-b'

      - name: Remote check
        run: |
	  ls -al

