name: Remote image build. 
run-name: Build triggered for branch ${{ github.event.inputs.branch }}.
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: main

env:
  organization: tskuit
  repository: blax-b

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Remote build
        uses: docker/setup-buildx-action@v2

      - name: Remote checkout blax-b repo ${{ github.event.inputs.branch }}
        uses: actions/checkout@v3
        with:
          path: 'blax-b-refix/'
          ref: "${{ github.event.inputs.branch }}"
          repository: "${{ env.organization }}/${{ env.repository }}"
##          repository: 'tskuit/blax-b'

